FROM python:3.12-bullseye

WORKDIR /app

# Hapus dependensi libGL, libXext, dll.
# libglib2.0-0 seringkali masih berguna untuk beberapa fungsionalitas OpenCV non-GUI.
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    libglib2.0-0 \
    # Jika Anda melakukan operasi terkait video, Anda mungkin perlu:
    # ffmpeg libsm6 libxext6 (meskipun headless, beberapa codec video bisa menarik ini)
    # Namun, coba minimal dulu.
    && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8080

CMD ["gunicorn", "app:app", "--bind", "0.0.0.0:8080"]