FROM python:3.12-slim

# Set workdir
WORKDIR /app

# Install system dependencies yang lengkap untuk OpenCV
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    libgl1-mesa-glx \
    libglib2.0-0 \
    libsm6 \
    libxrender1 \
    libxext6 && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Salin requirements
COPY requirements.txt .

# Install dependencies Python
RUN pip install --no-cache-dir -r requirements.txt

# Salin semua file proyek
COPY . .

# Expose port Flask
EXPOSE 8080

# Jalankan aplikasi dengan gunicorn
CMD ["gunicorn", "app:app", "--bind", "0.0.0.0:8080"]
